boot.o: boot.S multiboot.h x86_desc.h types.h
idt_.o: idt_.S
page_.o: page_.S
syscall_.o: syscall_.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h types.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h types.h x86_desc.h lib.h i8259.h keyboard.h rtc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h page.h rtc.h keyboard.h filesys.h
keyboard.o: keyboard.c lib.h types.h i8259.h keyboard.h tests.h
lib.o: lib.c lib.h types.h
page.o: page.c page.h types.h lib.h
rtc.o: rtc.c lib.h types.h rtc.h i8259.h tests.h
syscall.o: syscall.c syscall.h types.h filesys.h
terminal.o: terminal.c terminal.h lib.h types.h keyboard.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h page.h terminal.h \
  keyboard.h rtc.h syscall.h filesys.h
