boot.o: boot.S multiboot.h x86_desc.h types.h
idt_.o: idt_.S
page_.o: page_.S
syscall_.o: syscall_.S
x86_desc.o: x86_desc.S x86_desc.h types.h
dynamic_alloc.o: dynamic_alloc.c dynamic_alloc.h lib.h types.h page.h
filesys.o: filesys.c filesys.h types.h lib.h process.h keyboard.h \
  signal.h scheduling.h i8259.h terminal.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h types.h x86_desc.h lib.h i8259.h keyboard.h rtc.h \
  scheduling.h process.h filesys.h signal.h syscall.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h page.h rtc.h keyboard.h filesys.h terminal.h process.h signal.h \
  scheduling.h dynamic_alloc.h
keyboard.o: keyboard.c lib.h types.h i8259.h keyboard.h tests.h \
  terminal.h process.h filesys.h signal.h page.h scheduling.h
lib.o: lib.c lib.h types.h terminal.h keyboard.h process.h filesys.h \
  signal.h scheduling.h i8259.h
page.o: page.c page.h types.h lib.h terminal.h keyboard.h process.h \
  filesys.h signal.h scheduling.h i8259.h
process.o: process.c process.h types.h filesys.h keyboard.h signal.h \
  syscall.h
rtc.o: rtc.c lib.h types.h rtc.h i8259.h tests.h scheduling.h process.h \
  filesys.h keyboard.h signal.h terminal.h
scheduling.o: scheduling.c scheduling.h i8259.h types.h process.h \
  filesys.h keyboard.h signal.h idt.h page.h lib.h terminal.h x86_desc.h \
  syscall.h
signal.o: signal.c signal.h types.h dynamic_alloc.h lib.h process.h \
  filesys.h keyboard.h
syscall.o: syscall.c syscall.h types.h filesys.h keyboard.h terminal.h \
  lib.h process.h signal.h page.h idt.h x86_desc.h scheduling.h i8259.h
terminal.o: terminal.c terminal.h lib.h types.h keyboard.h process.h \
  filesys.h signal.h page.h x86_desc.h syscall.h scheduling.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h page.h terminal.h \
  keyboard.h process.h filesys.h signal.h rtc.h syscall.h scheduling.h \
  i8259.h dynamic_alloc.h
